# Generated by Django 4.1.1 on 2022-09-09 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_tareas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Descripcion", models.CharField(default="", max_length=500)),
                ("fecha_creacion", models.DateField(default=datetime.date.today)),
                ("fecha_entrega", models.DateField(null=True)),
                ("usuario_responsable", models.CharField(default="0", max_length=128)),
                (
                    "estado_tarea",
                    models.CharField(default="Programado", max_length=128),
                ),
            ],
        ),
    ]
