# Generated by Django 4.1.1 on 2022-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_tareas", "0002_tarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tarea",
            field=models.CharField(default="", max_length=128),
        ),
    ]
